package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// WatchedRepoSpec declares which Git manifests to check against which
// namespace, and how often.
type WatchedRepoSpec struct {
	// RepoURL is the Git repository to clone, e.g. https://github.com/org/repo.git
	RepoURL string `json:"repoURL"`

	// Branch to check out. Defaults to the repo's default branch.
	// +optional
	Branch string `json:"branch,omitempty"`

	// Path within the repo to the directory of YAML manifests.
	Path string `json:"path"`

	// Namespace in the cluster to compare the manifests against.
	Namespace string `json:"namespace"`

	// PollInterval between checks, e.g. "5m". Defaults to 5m.
	// +optional
	PollInterval string `json:"pollInterval,omitempty"`

	// Ignore lists "Kind/name" entries excluded from orphan detection, in
	// addition to well-known cluster-managed resources.
	// +optional
	Ignore []string `json:"ignore,omitempty"`

	// AutoRemediate applies Git's version automatically to fix MISSING and
	// DRIFTED resources (via server-side apply), instead of only reporting
	// them. Off by default.
	// +optional
	AutoRemediate bool `json:"autoRemediate,omitempty"`

	// PruneOrphans additionally deletes resources that are running in the
	// cluster but not declared in Git. Has no effect unless AutoRemediate
	// is also true. Off by default — this is destructive.
	// +optional
	PruneOrphans bool `json:"pruneOrphans,omitempty"`
}

// DriftEntry describes one resource that isn't in sync.
type DriftEntry struct {
	Kind   string `json:"kind"`
	Name   string `json:"name"`
	Status string `json:"status"`
	// +optional
	Detail string `json:"detail,omitempty"`
}

// WatchedRepoStatus reports the result of the most recent check.
type WatchedRepoStatus struct {
	// +optional
	LastChecked metav1.Time `json:"lastChecked,omitempty"`
	InSync      bool        `json:"inSync"`
	DriftCount  int         `json:"driftCount"`
	// +optional
	Drift []DriftEntry `json:"drift,omitempty"`
	// +optional
	Error string `json:"error,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="In Sync",type=boolean,JSONPath=".status.inSync"
// +kubebuilder:printcolumn:name="Drift",type=integer,JSONPath=".status.driftCount"
// +kubebuilder:printcolumn:name="Last Checked",type=string,JSONPath=".status.lastChecked"

// WatchedRepo represents one Git-repo-vs-cluster drift check.
type WatchedRepo struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   WatchedRepoSpec   `json:"spec,omitempty"`
	Status WatchedRepoStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WatchedRepoList is a list of WatchedRepo.
type WatchedRepoList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WatchedRepo `json:"items"`
}

// The DeepCopy methods below are normally generated by controller-gen; they
// are hand-written here to avoid depending on that tool being installed.

func (in *WatchedRepoSpec) DeepCopyInto(out *WatchedRepoSpec) {
	*out = *in
	if in.Ignore != nil {
		out.Ignore = make([]string, len(in.Ignore))
		copy(out.Ignore, in.Ignore)
	}
}

func (in *WatchedRepoSpec) DeepCopy() *WatchedRepoSpec {
	if in == nil {
		return nil
	}
	out := new(WatchedRepoSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DriftEntry) DeepCopyInto(out *DriftEntry) {
	*out = *in
}

func (in *DriftEntry) DeepCopy() *DriftEntry {
	if in == nil {
		return nil
	}
	out := new(DriftEntry)
	in.DeepCopyInto(out)
	return out
}

func (in *WatchedRepoStatus) DeepCopyInto(out *WatchedRepoStatus) {
	*out = *in
	in.LastChecked.DeepCopyInto(&out.LastChecked)
	if in.Drift != nil {
		out.Drift = make([]DriftEntry, len(in.Drift))
		copy(out.Drift, in.Drift)
	}
}

func (in *WatchedRepoStatus) DeepCopy() *WatchedRepoStatus {
	if in == nil {
		return nil
	}
	out := new(WatchedRepoStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *WatchedRepo) DeepCopyInto(out *WatchedRepo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *WatchedRepo) DeepCopy() *WatchedRepo {
	if in == nil {
		return nil
	}
	out := new(WatchedRepo)
	in.DeepCopyInto(out)
	return out
}

func (in *WatchedRepo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *WatchedRepoList) DeepCopyInto(out *WatchedRepoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]WatchedRepo, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *WatchedRepoList) DeepCopy() *WatchedRepoList {
	if in == nil {
		return nil
	}
	out := new(WatchedRepoList)
	in.DeepCopyInto(out)
	return out
}

func (in *WatchedRepoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
